# -*- coding: utf-8 -*-
"""Metode simpson

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-khyB_uamm9Zx3UM3Buci5uv23KVoQjW
"""

# Mengimport Library
import numpy as np
import matplotlib.pyplot as plt

# Fungsi yang akan diintegralkan
def func(x):
    return x**(-3) + np.cos(x)

# Batas integrasi
a = 1.0  # Batas bawah
b = 5.0  # Batas atas
n = 10 # Jumlah grid

# Simpson's Rule
if n % 2 == 0:
    n += 1  # Jika n genap, tambah 1 agar menjadi ganjil

x = np.linspace(a, b, n)
dx = (x[-1] - x[0]) / (n - 1)

# Menghitung integral menggunakan metode Simpson
hasil = func(x[0]) + func(x[-1])  # Tambah f(a) dan f(b)

for i in range(1, n-1, 2):
    hasil += 4 * func(x[i])  # Untuk indeks ganjil

for i in range(2, n-2, 2):
    hasil += 2 * func(x[i])  # Untuk indeks genap

hasil *= dx / 3  # Faktor dx/3

# Visualisasi grafik dan bar
xp = np.linspace(a, b, 1000)
plt.plot(xp, func(xp))

for i in range(n):
    plt.bar(x[i], func(x[i]), align='edge', width=dx, color='red', edgecolor='black')
plt.show()
print(hasil)