# -*- coding: utf-8 -*-
"""Metode trapezoid soal no 1b

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fehcZ2Xr3YOLDnArSSzCbI5ct3W2FnwY
"""

# mengimport library
import numpy as np
import matplotlib.pyplot as plt

# Integral
def func(x):           #Nama Fungsi
    return x**(-3) + np.cos(x)  # Fungsi yang akan diintegralkan

a = 1.0
b = 5.0

#metode trapezoid
n = 10 # Jumlah partisi yang digunakan
dx = (b - a) / (n - 1)
x = np.linspace(a, b, n)

sigma = 0
for i in range(1, n - 1):
    sigma += func(x[i])

hasil = 0.5 * dx * (func(x[0]) + 2 * sigma + func(x[-1]))

print(hasil)

xp = np.linspace(a, b, 1000)
plt.plot(xp, func(xp))
plt.show()

xp = np.linspace(a, b, 1000)
plt.plot(xp, func(xp))  # Plot kurva fungsi

# Loop untuk menggambar bar plot
for i in range(n):
    plt.bar(x[i], func(x[i]), align='edge', width=0.000001, edgecolor='red')

# Tampilkan grafik setelah semua bar plot digambar
plt.show()

xp = np.linspace(a, b, 1000)
plt.plot(xp, func(xp))# Plot kurva fungsi dengan warna kuning

# Loop untuk menggambar bar plot
for i in range(n):
    plt.bar(x[i], func(x[i]), align='edge', width = 0.000001, edgecolor='red')

# Isi area di bawah kurva dengan warna kuning
plt.fill_between(xp, func(xp), color='yellow', alpha=0.5)

# Tampilkan grafik setelah semua bar plot digambar
plt.show()